# 🚀 머신러닝 실습 : 고객 구매 데이터로 성별 예측 모델링 (분류 문제)

* 주어진 데이터는 백화점 고객의 1년 간 구매 데이터입니다.
* 고객 3,500명에 대한 학습용 데이터(y.csv, X.csv)를 이용하여 성별예측 모형을 만들어보세요.
* 모델의 성능은 자유롭게 측정해봅니다!

## [실습 프로세스]
1. 데이터 불러오기  
2. 데이터 탐색
3. 데이터 전처리  
4. 학습/테스트 데이터 분리  
5. 모델 선택 및 학습  
6. 예측 및 평가  


<br/>

---

<br/>
<br/>

# 0. 라이브러리 불러오기

* 라이브러리를 가져와서 과정을 준비합니다

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings(action='ignore')

<br/>

---

<br/>
<br/>

# 1. 데이터 불러오기
* 데이터를 가져와서 과정을 준비합시다.
- 인코딩 방식은 'euc-kr' 을 활용하세요.
- 데이터 출처 : 한국데이터산업진흥원 빅데이터분석기사 실기 공개 예시 문항

- 독립 변수 데이터셋 : ./data/X.csv
- 종속 변수 데이터셋 : ./data/y.csv


데이터 파일을 불러옵니다. 보통 CSV 파일을 pandas로 읽어옵니다.

In [3]:
import os
# 노트북 파일이 있는 폴더로 이동 (예시)
os.chdir(r'C:\githome\hipython_rep')

# 변경 후 확인
print("변경 후:", os.getcwd())

변경 후: c:\githome\hipython_rep


In [121]:
X_orgin = pd.read_csv('./data1/X.csv', encoding='euc-kr')
y = pd.read_csv('./data1/y.csv', encoding='euc-kr')

<br/>

---

<br/>
<br/>

# 2. 데이터 탐색하기
* 데이터를 이해할 수 있도록 탐색과정을 수행해봅시다.


데이터의 상위 몇 개 행을 출력하여 전체 구조를 미리 확인합니다.


데이터의 요약 정보나 통계 정보를 출력해 변수들의 유형과 분포를 확인합니다.


데이터의 요약 정보나 통계 정보를 출력해 변수들의 유형과 분포를 확인합니다.

In [9]:
X.head() # 고객 ID/ 총구매액, 최대구매액, 환불금액(float64), 주구매상품(object) ,주구매지점(object), 내점일수, 내점당 구매건수(float64), 주말방문비율(float64), 구매주기
y.head() # 고객 ID / 성별 
X.info() # 총 인덱스 3500개 환불금액만 결측치 존재 
y.info() # 총 인덱스 3500개 결측치 없음 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cust_id  3500 non-null   int64  
 1   총구매액     3500 non-null   int64  
 2   최대구매액    3500 non-null   int64  
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   object 
 5   주구매지점    3500 non-null   object 
 6   내점일수     3500 non-null   int64  
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(5), object(2)
memory usage: 273.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cust_id  3500 non-null   int64
 1   gender   3500 non-null   int64
dtypes: int64(2)
memory usage: 54.8 KB


<br/>

---

<br/>
<br/>

# 3. 데이터 전처리
* 전처리 과정을 통해서 머신러닝에 사용할 수 있는 형태의 데이터 준비


필요한 라이브러리를 불러옵니다.
- 인코딩 : LabelEncoder
- 데이터 표준화 : StandardScaler

* 단순히 1부터의 숫자를 부여한 'cust_id'를 수치형 변수로 받아들이면, 결과가 왜곡될 수 있으니 컬럼을 제거합니다.

In [ ]:
from sklearn.preprocessing import StandardScaler , LabelEncoder
X1= X_orgin.drop('cust_id', axis=1,inplace=False)
X1.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   int64  
 1   최대구매액    3500 non-null   int64  
 2   환불금액     1205 non-null   float64
 3   주구매상품    3500 non-null   object 
 4   주구매지점    3500 non-null   object 
 5   내점일수     3500 non-null   int64  
 6   내점당구매건수  3500 non-null   float64
 7   주말방문비율   3500 non-null   float64
 8   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 246.2+ KB


In [156]:
X1

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기  \
0      68282840  11264000  6860000.0    19  3.894737  0.527027    17   
1       2136000   2136000   300000.0     2  1.500000  0.000000     1   
2       3197000   1639000        0.0     2  2.000000  0.000000     1   
3      16077620   4935000        0.0    18  2.444444  0.318182    16   
4      29050000  24000000        0.0     2  1.500000  0.000000    85   
...         ...       ...        ...   ...       ...       ...   ...   
3495    3175200   3042900        0.0     1  2.000000  1.000000     0   
3496   29628600   7200000  6049600.0     8  1.625000  0.461538    40   
3497      75000     75000        0.0     1  1.000000  0.000000     0   
3498    1875000   1000000        0.0     2  1.000000  0.000000    39   
3499  263101550  34632000  5973000.0    38  2.421053  0.467391     8   

      주구매상품encoded  주구매지점encoded  iencoded      방문당평균구매액      환불비율  총구매건수  \
0                5             0         0  3.593834e+06  0.100464   74.0   
1               21            19        19  1.068000e+06  0.140449    3.0   
2                6             1         1  1.598500e+06  0.000000    4.0   
3                5             2         2  8.932011e+05  0.000000   44.0   
4               15             8         8  1.452500e+07  0.000000    3.0   
...            ...           ...       ...           ...       ...    ...   
3495             3             8         8  3.175200e+06  0.000000    2.0   
3496            22             9         9  3.703575e+06  0.204181   13.0   
3497            32            21        21  7.500000e+04  0.000000    1.0   
3498            41             8         8  9.375000e+05  0.000000    2.0   
3499             5             8         8  6.923725e+06  0.022702   92.0   

      잠재고객충성도  
0         323  
1           2  
2           2  
3         288  
4         170  
...       ...  
3495        0  
3496      320  
3497        0  
3498       78  
3499      304  

[3500 rows x 14 columns]

- 데이터에 결측치가 있는지 확인해보세요


- 결측치에 0으로 채워 넣어 모델 학습에 지장이 없도록 합니다.

In [16]:
X1['환불금액'].fillna(0, inplace=True) # 결측치값 채우기


문자형 범주 데이터를 숫자로 바꾸기 위한 인코딩을 수행합니다.

각 데이터에 표준화를 적용하여 데이터의 스케일(크기 차이)을 맞춰줍니다.
- 평균을 0, 표준편차를 1로 맞춰서 → 데이터가 정규 분포 형태로 변환되도록 하세요

In [18]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   int64  
 1   최대구매액    3500 non-null   int64  
 2   환불금액     3500 non-null   float64
 3   주구매상품    3500 non-null   object 
 4   주구매지점    3500 non-null   object 
 5   내점일수     3500 non-null   int64  
 6   내점당구매건수  3500 non-null   float64
 7   주말방문비율   3500 non-null   float64
 8   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 246.2+ KB


In [32]:
import pandas as pd

le = LabelEncoder() # 인코더 객체 생성
li = X1.select_dtypes(include='object').columns.tolist()
li



['주구매상품', '주구매지점']

In [35]:
for i in li:
    X1[i+'encoded'] = le.fit_transform(X1[i])
    print(X1)

           총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수    주말방문비율  \
0      68282840  11264000  6860000.0      기타   강남점    19  3.894737  0.527027   
1       2136000   2136000   300000.0     스포츠   잠실점     2  1.500000  0.000000   
2       3197000   1639000        0.0  남성 캐주얼   관악점     2  2.000000  0.000000   
3      16077620   4935000        0.0      기타   광주점    18  2.444444  0.318182   
4      29050000  24000000        0.0      보석  본  점     2  1.500000  0.000000   
...         ...       ...        ...     ...   ...   ...       ...       ...   
3495    3175200   3042900        0.0      골프  본  점     1  2.000000  1.000000   
3496   29628600   7200000  6049600.0    시티웨어  부산본점     8  1.625000  0.461538   
3497      75000     75000        0.0    주방용품   창원점     1  1.000000  0.000000   
3498    1875000   1000000        0.0     화장품  본  점     2  1.000000  0.000000   
3499  263101550  34632000  5973000.0      기타  본  점    38  2.421053  0.467391   

      구매주기  주구매상품encoded  주구매지점encoded 

In [ ]:
# 파생 변수 생성
X1["방문당평균구매액"] = X1["총구매액"] / X1["내점일수"]
X1["환불비율"] = X1["환불금액"] / X1["총구매액"]
X1["총구매건수"] = X1["내점일수"] * X1["내점당구매건수"]
X1["잠재고객충성도"] = X1["구매주기"] * X1["내점일수"]
X1["주말총방문수"] = X1["주말방문비율"] * X1["내점일수"]
X1[]

X1.replace([np.inf, -np.inf], np.nan, inplace=True)
X1.fillna(X1.mean(), inplace=True)

In [161]:
X1

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기  \
0      68282840  11264000  6860000.0    19  3.894737  0.527027    17   
1       2136000   2136000   300000.0     2  1.500000  0.000000     1   
2       3197000   1639000        0.0     2  2.000000  0.000000     1   
3      16077620   4935000        0.0    18  2.444444  0.318182    16   
4      29050000  24000000        0.0     2  1.500000  0.000000    85   
...         ...       ...        ...   ...       ...       ...   ...   
3495    3175200   3042900        0.0     1  2.000000  1.000000     0   
3496   29628600   7200000  6049600.0     8  1.625000  0.461538    40   
3497      75000     75000        0.0     1  1.000000  0.000000     0   
3498    1875000   1000000        0.0     2  1.000000  0.000000    39   
3499  263101550  34632000  5973000.0    38  2.421053  0.467391     8   

      주구매상품encoded  주구매지점encoded  iencoded      방문당평균구매액      환불비율  총구매건수  \
0                5             0         0  3.593834e+06  0.100464   74.0   
1               21            19        19  1.068000e+06  0.140449    3.0   
2                6             1         1  1.598500e+06  0.000000    4.0   
3                5             2         2  8.932011e+05  0.000000   44.0   
4               15             8         8  1.452500e+07  0.000000    3.0   
...            ...           ...       ...           ...       ...    ...   
3495             3             8         8  3.175200e+06  0.000000    2.0   
3496            22             9         9  3.703575e+06  0.204181   13.0   
3497            32            21        21  7.500000e+04  0.000000    1.0   
3498            41             8         8  9.375000e+05  0.000000    2.0   
3499             5             8         8  6.923725e+06  0.022702   92.0   

      잠재고객충성도  
0         323  
1           2  
2           2  
3         288  
4         170  
...       ...  
3495        0  
3496      320  
3497        0  
3498       78  
3499      304  

[3500 rows x 14 columns]

<br/>

---

<br/>
<br/>

# 5-1. 모델링 - LogisticRegression

* 본격적으로 모델을 선언하고 학습시킵니다.


필요한 라이브러리를 불러옵니다.

모델을 선언하여 객체화시킵니다.


모델을 학습 데이터에 맞춰 학습시킵니다.

In [38]:
X1.info()
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   총구매액          3500 non-null   int64  
 1   최대구매액         3500 non-null   int64  
 2   환불금액          3500 non-null   float64
 3   주구매상품         3500 non-null   object 
 4   주구매지점         3500 non-null   object 
 5   내점일수          3500 non-null   int64  
 6   내점당구매건수       3500 non-null   float64
 7   주말방문비율        3500 non-null   float64
 8   구매주기          3500 non-null   int64  
 9   주구매상품encoded  3500 non-null   int64  
 10  주구매지점encoded  3500 non-null   int64  
 11  iencoded      3500 non-null   int64  
dtypes: float64(3), int64(7), object(2)
memory usage: 328.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cust_id  3500 non-null   int64
 1   gender  

In [44]:
X1.drop('주구매상품',axis=1,inplace=True)
X1.drop('주구매지점',axis=1,inplace=True)

In [168]:
X1

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기  \
0      68282840  11264000  6860000.0    19  3.894737  0.527027    17   
1       2136000   2136000   300000.0     2  1.500000  0.000000     1   
2       3197000   1639000        0.0     2  2.000000  0.000000     1   
3      16077620   4935000        0.0    18  2.444444  0.318182    16   
4      29050000  24000000        0.0     2  1.500000  0.000000    85   
...         ...       ...        ...   ...       ...       ...   ...   
3495    3175200   3042900        0.0     1  2.000000  1.000000     0   
3496   29628600   7200000  6049600.0     8  1.625000  0.461538    40   
3497      75000     75000        0.0     1  1.000000  0.000000     0   
3498    1875000   1000000        0.0     2  1.000000  0.000000    39   
3499  263101550  34632000  5973000.0    38  2.421053  0.467391     8   

      주구매상품encoded  주구매지점encoded  iencoded      방문당평균구매액      환불비율  총구매건수  \
0                5             0         0  3.593834e+06  0.100464   74.0   
1               21            19        19  1.068000e+06  0.140449    3.0   
2                6             1         1  1.598500e+06  0.000000    4.0   
3                5             2         2  8.932011e+05  0.000000   44.0   
4               15             8         8  1.452500e+07  0.000000    3.0   
...            ...           ...       ...           ...       ...    ...   
3495             3             8         8  3.175200e+06  0.000000    2.0   
3496            22             9         9  3.703575e+06  0.204181   13.0   
3497            32            21        21  7.500000e+04  0.000000    1.0   
3498            41             8         8  9.375000e+05  0.000000    2.0   
3499             5             8         8  6.923725e+06  0.022702   92.0   

      잠재고객충성도  
0         323  
1           2  
2           2  
3         288  
4         170  
...       ...  
3495        0  
3496      320  
3497        0  
3498       78  
3499      304  

[3500 rows x 14 columns]

In [122]:
X_orgin

cust_id       총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0           0   68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1           1    2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2           2    3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3           3   16077620   4935000        NaN      기타   광주점    18  2.444444   
4           4   29050000  24000000        NaN      보석  본  점     2  1.500000   
...       ...        ...       ...        ...     ...   ...   ...       ...   
3495     3495    3175200   3042900        NaN      골프  본  점     1  2.000000   
3496     3496   29628600   7200000  6049600.0    시티웨어  부산본점     8  1.625000   
3497     3497      75000     75000        NaN    주방용품   창원점     1  1.000000   
3498     3498    1875000   1000000        NaN     화장품  본  점     2  1.000000   
3499     3499  263101550  34632000  5973000.0      기타  본  점    38  2.421053   

        주말방문비율  구매주기  
0     0.527027    17  
1     0.000000     1  
2     0.000000     1  
3     0.318182    16  
4     0.000000    85  
...        ...   ...  
3495  1.000000     0  
3496  0.461538    40  
3497  0.000000     0  
3498  0.000000    39  
3499  0.467391     8  

[3500 rows x 10 columns]

In [169]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   총구매액          3500 non-null   int64  
 1   최대구매액         3500 non-null   int64  
 2   환불금액          3500 non-null   float64
 3   내점일수          3500 non-null   int64  
 4   내점당구매건수       3500 non-null   float64
 5   주말방문비율        3500 non-null   float64
 6   구매주기          3500 non-null   int64  
 7   주구매상품encoded  3500 non-null   int64  
 8   주구매지점encoded  3500 non-null   int64  
 9   iencoded      3500 non-null   int64  
 10  방문당평균구매액      3500 non-null   float64
 11  환불비율          3500 non-null   float64
 12  총구매건수         3500 non-null   float64
 13  잠재고객충성도       3500 non-null   int64  
dtypes: float64(6), int64(8)
memory usage: 382.9 KB


In [194]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# X1["방문당평균구매액"] = X1["총구매액"] / X1["내점일수"]
# X1["환불비율"] = X1["환불금액"] / X1["총구매액"]
# X1["총구매건수"] = X1["내점일수"] * X1["내점당구매건수"]
# X1["잠재고객충성도"] = X1["구매주기"] * X1["내점일수"]

X = X1[['내점일수','내점당구매건수','주구매상품encoded'
        ,'방문당평균구매액','환불비율','잠재고객충성도']]
Y = y[['gender']]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,                 # 데이터프레임 기준
                                                    test_size=0.2,        # 테스트셋 비율 (20%)
                                                    random_state=3        # 재현 가능성 유지
                                                    )

lomodel = LogisticRegression(max_iter=3000)
lomodel.fit(X_train, Y_train)
pred = lomodel.predict(X_test)
acc = accuracy_score(Y_test, pred)
print(f'acc = {acc}')

acc = 0.66


In [188]:
import numpy as np
np.isinf(X_train).sum().sum(), np.isnan(X_train).sum().sum()

(np.int64(0), np.int64(0))

In [195]:
from sklearn.preprocessing import StandardScaler
Sc_x = StandardScaler()
Sc_x.fit(X_train)
x_train_sc = Sc_x.transform(X_train)
x_test_sc = Sc_x.transform(X_test)

In [196]:
from sklearn.ensemble import RandomForestClassifier
rd_model = RandomForestClassifier(random_state=18, max_depth=12)
rd_model.fit(x_train_sc, Y_train)
rd_pred = rd_model.predict(x_test_sc)
rd_acc = accuracy_score(Y_test,rd_pred)
rd_acc

0.6471428571428571

In [198]:
from sklearn.model_selection import GridSearchCV
params = {'max_depth':[9,10,11], 'min_samples_split':[4,7,8], 'n_estimators':[300]}
grid_tree = GridSearchCV(rd_model, param_grid=params, cv=3, refit=True)
grid_tree.fit(x_train_sc, Y_train)

GridSearchCV(cv=3,
             estimator=RandomForestClassifier(max_depth=12, random_state=18),
             param_grid={'max_depth': [9, 10, 11],
                         'min_samples_split': [4, 7, 8],
                         'n_estimators': [300]})

In [199]:
grid_tree.best_params_

{'max_depth': 9, 'min_samples_split': 4, 'n_estimators': 300}

In [200]:
best_rf = grid_tree.best_estimator_
rd_pred_pa = best_rf.predict(x_test_sc)
accuracy_score(Y_test,rd_pred_pa)

0.6614285714285715

로지스틱 회귀 

In [201]:
lomodel = LogisticRegression()
lomodel.fit(x_train_sc, Y_train)
lo_pred = lomodel.predict(x_test_sc)
acc = accuracy_score(Y_test, lo_pred)
print(f'acc = {acc}')

acc = 0.6442857142857142


<br/>

---

<br/>
<br/>

# 6-1. 예측 성능 확인해보기 - LogisticRegression

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [77]:
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score

confusion_matrix(Y_test,  lo_pred)

array([[412,  29],
       [222,  37]])

In [78]:
def get_clf_eval(Y_test, pred):
    confusion = confusion_matrix(Y_test, pred)
    accuracy = accuracy_score(Y_test, pred) # 전체 샘플 중에서 예측을 맞춘 비율
    precision = precision_score(Y_test, pred) # 모델이 1이라고 예측한 것들 중 실제로 1인 비율
    recall = recall_score(Y_test, pred) #실제로 1인 것들 중에 모델이 1이라고 맞춘 비율

    print(confusion)
    print('',20)
    print(accuracy, precision, recall)

In [79]:
get_clf_eval(Y_test, lo_pred)

[[412  29]
 [222  37]]
 20
0.6414285714285715 0.5606060606060606 0.14285714285714285



<br/>

---

<br/>
<br/>

# 5-2. 모델링 - DecisionTreeClassifier

* 본격적으로 모델을 선언하고 학습시킵니다.


필요한 라이브러리를 불러옵니다.

모델을 선언하여 객체화시킵니다.

모델을 학습 데이터에 맞춰 학습시킵니다.

In [80]:
from sklearn.tree import DecisionTreeClassifier

de_model = DecisionTreeClassifier()
de_model.fit(x_train_sc, Y_train)
de_pred = de_model.predict(x_test_sc)
acc = accuracy_score(Y_test, de_pred)
acc

0.5614285714285714



<br/>
<br/>

# 6-2. 예측 성능 확인해보기 - DecisionTreeClassifier

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [81]:

get_clf_eval(Y_test, de_pred)

[[292 149]
 [158 101]]
 20
0.5614285714285714 0.404 0.38996138996138996



<br/>

---

<br/>
<br/>

# 5-3. 모델링 - RandomForestClassifier

* 본격적으로 모델을 선언하고 학습시킵니다.



필요한 라이브러리를 불러옵니다.

모델을 선언하여 객체화시킵니다.

모델을 학습 데이터에 맞춰 학습시킵니다.

In [128]:
from sklearn.ensemble import RandomForestClassifier
rd_model = RandomForestClassifier(random_state=20, max_depth=8)
rd_model.fit(x_train_sc, Y_train)
rd_pred = rd_model.predict(x_test_sc)
rd_acc = accuracy_score(Y_test,rd_pred)
rd_acc

0.6528571428571428

In [132]:
from sklearn.model_selection import GridSearchCV
params = {'max_depth':[4,5,6], 'min_samples_split':[1,2,3], 'n_estimators':[300]}
grid_tree = GridSearchCV(rd_model, param_grid=params, cv=3, refit=True)
grid_tree.fit(x_train_sc, Y_train)

GridSearchCV(cv=3,
             estimator=RandomForestClassifier(max_depth=8, random_state=20),
             param_grid={'max_depth': [4, 5, 6], 'min_samples_split': [1, 2, 3],
                         'n_estimators': [300]})

In [133]:
grid_tree.best_params_

{'max_depth': 5, 'min_samples_split': 3, 'n_estimators': 300}

In [134]:
best_rf = grid_tree.best_estimator_
rd_pred_pa = best_rf.predict(x_test_sc)
accuracy_score(Y_test,rd_pred_pa)

0.6585714285714286



<br/>
<br/>

# 6-3. 예측 성능 확인해보기 - RandomForestClassifier

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [120]:
def get_clf_eval(Y_test, pred):
    confusion = confusion_matrix(Y_test, pred)
    accuracy = accuracy_score(Y_test, pred) # 전체 샘플 중에서 예측을 맞춘 비율
    precision = precision_score(Y_test, pred) # 모델이 1이라고 예측한 것들 중 실제로 1인 비율
    recall = recall_score(Y_test, pred) #실제로 1인 것들 중에 모델이 1이라고 맞춘 비율

    print(confusion)
    print('',20)
    print(accuracy, precision, recall)

get_clf_eval(Y_test, rd_pred_pa)

[[415  26]
 [225  34]]
 20
0.6414285714285715 0.5666666666666667 0.13127413127413126



<br/>

---

<br/>
<br/>

# 5-4. 모델링 - XGBoost

* 본격적으로 모델을 선언하고 학습시킵니다.



필요한 라이브러리를 불러옵니다.

모델을 선언하여 객체화시킵니다.

모델을 학습 데이터에 맞춰 학습시킵니다.

In [94]:

import xgboost
from sklearn.preprocessing import LabelEncoder

In [96]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

# 모델 생성 및 학습
xg_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xg_model.fit(x_train_sc, Y_train)

# 예측 및 평가
xg_pred = xg_model.predict(x_test_sc)
print("정확도:", accuracy_score(Y_test, xg_pred))


정확도: 0.6071428571428571




<br/>
<br/>

# 6-4. 예측 성능 확인해보기 - XGBoost

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [97]:
get_clf_eval(Y_test, xg_pred)

[[330 111]
 [164  95]]
 20
0.6071428571428571 0.46116504854368934 0.3667953667953668


<br/>

---


<br/>

## 7.  위 4가지 모델의 학습 & 예측 & 평가 결과를 확인하고 최고 성능을 내는 모델을 찾아봅시다!

- 어떤 모델이 가장 성능이 좋은가요 ?

In [104]:
from sklearn.model_selection import GridSearchCV


model = {
            'log' : lomodel,
            'de'  : de_model,
            'rd'  : rd_model
            # 'xgb' : xg_model
}

for i, md in model.items():
    params = {'max_depth':[1,2,3], 'min_samples_split':[1,2,3], 'n_estimators':[200]}
    grid_tree = GridSearchCV(md, param_grid=params, cv=3, refit=True)
    grid_tree.fit(x_train_sc, Y_train)

ValueError: Invalid parameter 'max_depth' for estimator LogisticRegression(). Valid parameters are: ['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'].

In [202]:
get_clf_eval(Y_test, lo_pred) #로지스틱회귀 
get_clf_eval(Y_test, de_pred) #선택나무
get_clf_eval(Y_test, rd_pred_pa) # 랜덤포레스트 파라미터
get_clf_eval(Y_test, xg_pred) #xgboost

[[386  77]
 [172  65]]
 20
0.6442857142857142 0.45774647887323944 0.2742616033755274
[[303 160]
 [147  90]]
 20
0.5614285714285714 0.36 0.379746835443038
[[378  85]
 [152  85]]
 20
0.6614285714285715 0.5 0.35864978902953587
[[330 133]
 [164  73]]
 20
0.5757142857142857 0.35436893203883496 0.3080168776371308
